#!/usr/bin/env sh


USAGE="team <update> [-h]"
LONG_USAGE="---"


cmd_update() {
	update "$@"
}


update() {
	validate_git_clean_working_tree

	log "updating team..."

	local integration_branch="$(git config --global gitflux.branch.integration)"
	local team_branch="$(git config --global gitflux.branch.team)"
	log "team branch name: '$team_branch'."

	log "switching to the integration branch and updating from the remote..."
	git checkout "$integration_branch" >/dev/null 2>&1 && git pull >/dev/null 2>&1

	log "switching to the team branch and updating from the remote..."
	git checkout "$team_branch" >/dev/null 2>&1 && git pull >/dev/null 2>&1

	log "merging changes from the integration branch..."
    git merge --no-edit "$integration_branch" >/dev/null 2>&1 || {
		fatal "conflicts were found during merge, resolve them in your favorite merge tool."		
	}

	ok "team was updated."
}
