#!/usr/bin/env sh


USAGE="rc <start> <next-version> [-h]"
LONG_USAGE="---"


cmd_start() {
	# todo - revisit this to adapt to the new create_branch_from_base api
#	local next_version="$1"
#	create_branch_from_base "$(git_config_get "gitflux.prefix.rc")" "$(git_config_get "gitflux.branch.integration")" "$next_version"

	exit 0
#	local tag="v${next_version}-rc"
#	validate_git_tag_not_exists "$tag"
#	git_tag $tag "version '$next_version' release candidate"
#	git_push $tag
}
