#!/usr/bin/env sh


USAGE="integration <update> [-h]"
LONG_USAGE="---"


cmd_update() {
	update "$@"
}


update() {
	validate_git_clean_working_tree

	log "updating integration..."

	local integration_branch="$(git config --global le-gitflow.branch.integration)"

	log "switching to the master branch and updating from the remote..."
	git checkout master >/dev/null 2>&1 && git pull >/dev/null 2>&1

	log "switching to the integration branch and updating from the remote..."
	git checkout "$integration_branch" >/dev/null 2>&1 && git pull >/dev/null 2>&1

	log "merging changes from the master branch..."
	git merge --no-edit --no-ff master >/dev/null 2>&1

	ok "integration was updated."
}
