#!/usr/bin/env bash


working_dir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

# include common utilities first, to be able to use the text formatter with usage/long-usage messages
source "$working_dir/gitflux-common"



# indicates this git command can run from within child directories of the git repo
SUBDIRECTORY_OK="yes"

# output for stdout when calling the usage() function (can be overridden in each action)
USAGE="init|feature|team|integration|rc|hf [<action>] [<action-args>...] [-h]"

# appended to the usage output when using the `-h` flag (can be overridden in each action)
LONG_USAGE="\
$(t_heading "git-flux")

git commands for fluent, team-oriented workflow.


$(t_subheading "flags")

$(t_code_definition \
"-h" \
"shows the f***ing manual. works everywhere, and context dependent.
this means you can $(t_code "git flux -h"), and also $(t_code "git flux feature -h") \
or $(t_code "git flux feature start -h")." \
)

$(t_subheading "available subcommands")

$(t_code_definition \
"init" \
"initialize the git-flux configuration survey." \
)
$(t_code_definition \
"$(t_fg_blue "feature")" \
"handle feature level actions." \
)
$(t_code_definition \
"$(t_fg_yellow "team")" \
"handle integration across team members and their features." \
)
$(t_code_definition \
"$(t_fg_magenta "integration")" \
"handle integration across teams." \
)
$(t_code_definition \
"$(t_fg_green "rc")" \
"handle lifecycle of release-candidates." \
)
$(t_code_definition \
"$(t_fg_red "hf")" \
"handle lifecycle of hot-fixes." \
)

refer to each subcommand's help menu for an in-depth description of its actions (e.g. $(t_code "git flux init -h")).
 "
# ^ single space on the last line of long-usage is used to add a line-break


main() {
	
	# a little nice backdoor for debugging :)
	if [[ $1 = "debug" ]]; then
		set -x; shift
	fi

	local sub_command="$1";

	# lose the sub-command arg only if it's not an `-h` flag, to not break long-usage
	[[ -n $1 && $1 != "-h" ]] && shift

	# verify the sub-command script exists, and include it
	if [[ -e "$working_dir/git-flux-$sub_command" ]]; then
		source "$working_dir/git-flux-$sub_command"
	fi

	local action="$1";

	# lose the action arg only if it's not an `-h` flag, to not break long-usage
	[[ -n $1 && $1 != "-h" ]] && shift

	if [[ -z $action || $action = "-h" ]]; then
		action="default"
	fi	
	
	# explicitly override usage/long-usage from the loaded sub-command per action
	if is_available "cmd_usage_$action"; then
		USAGE="$sub_command $(cmd_usage_${action})"
	fi
	if is_available "cmd_long_usage_$action"; then
		LONG_USAGE="$(cmd_long_usage_${action})"
	fi

	# include git builtin library 
	# this script have to be sourced after overriding USAGE/LONG_USAGE.
	# note that to output long-usage, usage() expects the first script argument to be `-h` when called, 
	# so shifting arguments can change the result.
	source "$(git --exec-path)/git-sh-setup"

	# verify the action function is available
	if ! is_available "cmd_$action"; then
		usage
	fi

	# validate action prerequisites
	if [[ $sub_command != "init" ]]; then
		require_gitflux_initialized
	fi

	# delegate to the sub-command action api
	cmd_${action} "$@"
}

main "$@"
