#!/usr/bin/env bash


cmd_usage_default() {
	printf "%s" "[-h]"
}

cmd_long_usage_default() {
	printf "%s" "\
$(f_heading "version")

shows the currently installed version.

$(f_italics '* since 0.4.0')
 "
}

cmd_default() {
	local version="$GIT_FLUX_VERSION"
	io_log; io_log_banner "git-flux version is: $version"; io_log
}
