#!/usr/bin/env sh

# todo - consider if/when updating from the team *remote* should be done. look for these:
# todo - git checkout "$(git config --global le-gitflow.branch.team)" && git pull

USAGE="feature <start|stop> [branch]"
LONG_USAGE="---"


cmd_start() {
	start "$@"
}

cmd_stop() {
	stop "$@"
}

cmd_update() {
	update "$@"
}


start() {
	echo "starting feature '$1'"

	validate_command "$1"

	local feature_branch="$(echo $1 | lower_dashes | prefix_feature_branch)"
	echo "feature branch name: '$feature_branch'"

	if git_local_branch_exists "$feature_branch"; then
		fatal "local branch '$feature_branch' already exists, what the damn hell are you doing?"
	fi

	echo "switching to the team branch and updating from the remote"
	git checkout "$(git config --global le-gitflow.branch.team)" >/dev/null 2>&1 && git pull >/dev/null 2>&1
	
	echo "creating the local feature branch and switching to it"
	git checkout -b "$feature_branch" >/dev/null 2>&1
	
	echo "pushing the feature branch to the remote"
	git push --set-upstream origin "$feature_branch" >/dev/null 2>&1

	ok "feature '$1' was started. happy coding!"
}

stop() {
	echo "stopping feature '$1'"
	
	validate_command "$1"

	printf "this will delete the feature's local and remote branches, continue? (y/n) "; read answer
	if [[ $answer = "y" ]]; then

		local feature_branch="$(echo $1 | lower_dashes | prefix_feature_branch)"
		echo "feature branch name: '$feature_branch'"

		echo "switching to the team branch and updating from the remote"
		git checkout "$(git config --global le-gitflow.branch.team)" >/dev/null 2>&1 && git pull >/dev/null 2>&1

		if git_local_branch_exists "$feature_branch"; then
			echo "deleting local branch"
			git branch -D "$feature_branch" >/dev/null 2>&1
		fi

		if git_remote_branch_exists "origin/$feature_branch"; then
			echo "deleting remote branch"
			git push --progress origin :"$feature_branch" >/dev/null 2>&1
		fi
		
		ok "feature '$1' was stopped. RIP."
	else
		fatal "i knew you'd chicken out."
	fi
}

update() {
	echo "updating feature '$1'"

	validate_command "$1"

	local feature_branch="$(echo $1 | lower_dashes | prefix_feature_branch)"
	echo "feature branch name: '$feature_branch'"

	if ! git_local_branch_exists "$feature_branch"; then
		fatal "feature branch '$feature_branch' does not exist locally, cannot update from team branch."
	fi

	echo "switching to the team branch and updating from the remote"
	git checkout "$(git config --global le-gitflow.branch.team)" >/dev/null 2>&1 && git pull >/dev/null 2>&1
	
	echo "switching back to the feature branch"
	git checkout "$feature_branch" >/dev/null 2>&1

	echo "merging changes from the team branch"
    git merge --no-edit --no-ff "$(git config --global le-gitflow.branch.team)" >/dev/null 2>&1

	ok "feature '$1' was updated."
}

prefix_feature_branch() {
	local prefix="$(git config --global le-gitflow.branch-prefix.feature)"
	local feature="$(input_from_arg_or_stdin $1)"
	echo "$prefix$feature"
}
