#!/usr/bin/env sh

USAGE="<feature|...> [action]"

main() {

	# include git utilities lib
	source "$(git --exec-path)/git-sh-setup"

	# no arguments, just show usage and quit
	if [ "$#" -lt 1 ]; then
		usage
	fi

	# retrieve the sub-command and remove it from the arguments list
	local sub_command="$1"; shift

	local working_dir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
	
	# include common utilities
	source "$working_dir/gitle-common"

	# verify the sub-command script exists
	if [ ! -e "$working_dir/git-le-$sub_command" ]; then
		usage
	fi

	# include the sub-command script
	source "$working_dir/git-le-$sub_command"


	# retrieve the action and remove it from the arguments list
	local action="$1"; shift

	# verify the action function is available
	if ! exists "cmd_$action"; then
		usage
	fi

	# delegate the sub_command to the appropriate action function
	cmd_${action} "$@"
}

main "$@"