#!/usr/bin/env bash


cmd_usage_default() {
	printf "start|finish|sync <name> [<base>] [-h]"
}

cmd_usage_start() {
	printf "start <name> [<base>] [-h]"
}

cmd_usage_finish() {
	printf "finish <name> [-h]"
}

cmd_usage_sync() {
	printf "sync <name> [-h]"
}

cmd_long_usage_default() {
	printf "\
$(t_heading "feature" | t_fg_blue)

handle feature level actions.


$(t_subheading "available actions")

$(cmd_long_usage_start)
$(cmd_long_usage_finish)
$(cmd_long_usage_sync)
"
}

cmd_long_usage_start() {
	printf "\
$(t_code_definition \
"$(cmd_usage_start)" \
"start a new feature; create a local branch and push it to the remote.
the branch name will be composed of the pre-configured feature prefix and the passed $(t_code "name").
pass an optional $(t_code "base") to set a custom base for the branch (default $(t_code "base") is the current team branch).")
 "
}

cmd_long_usage_finish() {
	printf "\
$(t_code_definition \
"$(cmd_usage_finish)" \
"finish an existing feature; delete its local and remote branches, for good.")
 "
}

cmd_long_usage_sync() {
	printf "\
$(t_code_definition \
"$(cmd_usage_sync)" \
"sync an existing feature with its base branch, usually the current team branch, unless otherwise set when the feature was started.")
 "
}


cmd_start() {
	require_args "$1"
	local team_branch="$(git_config_get "branch.team")"
	if [[ -z $team_branch && -z $2 ]]; then
		io_log; io_status_fatal "no base found!
      set up a team first with 'git flux team create' or 'git flux team join', or pass the base to this command."
	fi
	io_log; create_branch_from_base "$(git_config_get "prefix.feature")$1" "$team_branch" "$2"
	io_log; io_log_ok "feature '$1' is started. happy coding!"; io_log
}

cmd_finish() {
	require_args "$1"
	io_log; destroy_branch_from_base "$(git_config_get "prefix.feature")$1"
	io_log; io_log_ok "feature '$1' is finished. RIP."; io_log
}

cmd_sync() {
	require_args "$1"
	io_log; sync_branch_with_base "$(git_config_get "prefix.feature")$1"
	io_log; io_log_ok "feature '$1' is in sync with the base."; io_log
}
