#!/usr/bin/env sh


USAGE="team <create|destroy|sync|join> [-h]"
LONG_USAGE="---"


cmd_create() {
	action_start "$(git config --global gitflux.prefix.team)" "$(git config --global gitflux.branch.integration)" "$@"
}

cmd_destroy() {
	action_finish "$(git config --global gitflux.prefix.team)" "$@"
}

cmd_sync() {
	action_sync "$(git config --global gitflux.prefix.team)" "$@"
}

cmd_join() {
	action_switch "$(git config --global gitflux.prefix.team)" "team" "$@"
}
