#!/usr/bin/env sh


cmd_usage_default() {
	printf "<sync> [-h]"
}

cmd_usage_sync() {
	printf "sync [-h]"
}

cmd_long_usage_default() {
	printf "\
$(t_heading "integration" | t_fg_magenta)

handle integration across teams.


${t_under}available actions${t_under_off}

$(cmd_long_usage_sync)
"
}

cmd_long_usage_sync() {
	printf "\
   $(cmd_usage_sync | t_bold)
      pulls changes from the base branch, i.e. 'master', into the integration branch.
 "
}

cmd_sync() {
	local branch="$(git_config_get "branch.integration")"
	local base="master"
	io_log ; sync_branch_with_base "$branch" "$base"
	io_log; io_log_ok "'$branch' is in sync with '$base'."; io_log
}
