#!/usr/bin/env sh


USAGE="integration <sync> [-h]"
LONG_USAGE="---"


cmd_sync() {
	local branch="$(git_config_get "branch.integration")"
	local base="master"
	io_log "syncing '$branch' with '$base'..."
	sync_branch_with_base "$branch" "$base"
	io_log_ok "'$branch' is in sync with '$base'."
}
