#!/usr/bin/env sh


USAGE="feature <start|finish|sync|push|pull> <name> [base] [-h]"
LONG_USAGE="---"


cmd_start() {
	action_start "$(git config --global gitflux.prefix.feature)" "$(git config --global gitflux.branch.team)" "$@"
}

cmd_finish() {
	action_finish "$(git config --global gitflux.prefix.feature)" "$@"
}

cmd_sync() {
	action_sync "$(git config --global gitflux.prefix.feature)" "$@"
}
