#!/usr/bin/env bash


cmd_usage_default() {
	printf "%s" "[<tag>] [-h]"
}

cmd_long_usage_default() {
	printf "%s" "\
$(f_heading "update")

$(f_fg_rainbow "magically") updates git-flux.

pass a $(f_code 'tag') to get a specific version, or not, to get the latest and greatest.
tags are in the format $(f_code 'v#.#.#'), where each $(f_code '#') is a digit segment in a semantic-version string.

$(f_italics '* since 0.4.5')
 "
}

cmd_default() {
	io_log; self_update "$1"
	io_log; io_log_ok "git-flux is updated. $(f_fg_rainbow "it's magic")!"; io_log
}
