#!/usr/bin/env sh


validate_mandatory_arg() {
	if [[ -z $1 ]]; then
		usage
	fi
}

validate_git_flux_initialized() {
	if [[ $(git config --global gitflux.initialized) != true ]]; then
		io_status_fatal "git-flux is not initialized. you have to run 'git flux init' first."
	fi
}

validate_git_clean_working_tree() {
	if ! git_is_clean_working_tree; then
		io_status_fatal "working tree is not clean. please make sure all changes are commited, or stash them." 
	fi
}

validate_git_local_branch_exists() {
	if ! git_local_branch_exists "$1"; then
		io_status_fatal "branch '$1' don't exist locally."
	fi
}

validate_git_local_branch_not_exists() {
	if git_local_branch_exists "$1"; then
		io_status_fatal "branch '$1' already exists locally."
	fi
}

validate_git_remote_branch_exists() {
	if ! git_remote_branch_exists "origin/$1"; then
		io_status_fatal "branch '$1' don't exist on the remote."
	fi
}

validate_git_remote_branch_not_exists() {
	if git_remote_branch_exists "origin/$1"; then
		io_status_fatal "branch '$1' already exists on the remote."
	fi
}

validate_git_tag_exists() {
	if ! git_tag_exists "$1"; then
		io_status_fatal "tag '$1' don't exist."
	fi
}

validate_git_tag_not_exists() {
	if git_tag_exists "$1"; then
		io_status_fatal "tag '$1' already exists."
	fi
}
