#!/usr/bin/env sh


has() {
	local item=$1; shift
	echo " $@ " | grep -q " $(escape $item) "
}

is() {
	[[ -n $1 ]]
}

escape() {
	echo "$1" | sed 's/\([\.\$\*]\)/\\\1/g'
}

is_available() {
	type $1 >/dev/null 2>&1
}

strip_prefix() {
	echo "$1" | sed -e 's,^'"$2"',,'
}

repeat() {
    seq -f $1 -s '' $2; echo
}

# parses function input from stdin or passed arguments
# usage:
# local input=$(get_input "$@")
get_input() {
	local input
	if [ -t 0 ]; then
		if [ $# -gt 0 ]; then
			input="$*"
		fi
	else
		input=$(cat -)
	fi
	printf "%s" "$input"
}
