#!/usr/bin/env sh


# little ansi-based text formatters.

if [[ -n $FORMAT && $FORMAT = false ]]; then
	return;
fi

t_off=$(tput sgr0)
t_bold=$(tput bold)
t_under=$(tput smul)

if (( $(tput colors) >= 256 )); then
	t_fg_red=$(tput setaf 167)
	t_fg_green=$(tput setaf 107)
	t_fg_yellow=$(tput setaf 179)
	t_fg_blue=$(tput setaf 74)
	t_fg_magenta=$(tput setaf 182)
	t_fg_cyan=$(tput setaf 30)
	t_fg_lightred=$(tput setaf 174)
	t_fg_lightgreen=$(tput setaf 191)
	t_fg_lightyellow=$(tput setaf 222)
	t_fg_lightblue=$(tput setaf 153)
	t_fg_lightmagenta=$(tput setaf 219)
	t_fg_lightcyan=$(tput setaf 116)
fi

# uncomment the following line to see what it does:
# echo "text can be ${t_bold}bold${t_off}, ${t_under}underlined${t_off}, or colored in ${t_fg_yellow}yellow${t_off} or ${t_fg_blue}blue${t_off}"
# yay!
