#!/usr/bin/env bash


require_args() {
	for arg; do
		if [[ -z $arg ]]; then
			usage
		fi
	done
}

require_gitflux_initialized() {
	# todo - add global check!
	if [[ $(git_config_get "initialized") != true ]]; then
		io_log; io_status_fatal "git-flux is not initialized. run 'git flux init' to fix this."
	fi
}

require_non_empty_repository() {
	if git_repo_is_empty; then
		if ! git_pull_origin "master" && git_repo_is_empty; then
			io_log; io_status_fatal "repository is empty, add some changes to fix this."
		fi
	fi
}

validate_git_clean_working_tree() {
	if ! git_is_clean_working_tree; then
		io_status_fatal "working tree is not clean. make sure all changes are commited, or stash them." 
	fi
}

validate_git_local_branch_exists() {
	if ! git_local_branch_exists "$1"; then
		io_status_fatal "branch '$1' doesn't exist locally."
	fi
}

validate_git_remote_branch_exists() {
	if ! git_remote_branch_exists "$1"; then
		io_status_fatal "branch '$1' doesn't exist on the remote."
	fi
}

validate_git_local_branch_dont_exist() {
	if git_local_branch_exists "$1"; then
		io_status_fatal "branch '$1' already exists locally."
	fi
}

validate_git_remote_branch_dont_exist() {
	if git_remote_branch_exists "$1"; then
		io_status_fatal "branch '$1' already exists on the remote."
	fi
}

validate_git_local_and_remote_branches_exist() {
	validate_git_local_branch_exists "$1"
	validate_git_remote_branch_exists "$1"
}

validate_git_local_and_remote_branches_dont_exist() {
	validate_git_local_branch_dont_exist "$1"
	validate_git_remote_branch_dont_exist "$1"
}

validate_git_local_or_remote_branch_exists() {
	if ! git_branch_exists "$1"; then
		io_status_fatal "branch '$1' doesn't exist."
	fi
}

validate_git_tag_exists() {
	if ! git_tag_exists "$1"; then
		io_status_fatal "tag '$1' doesn't exist."
	fi
}

validate_git_tag_not_exists() {
	if git_tag_exists "$1"; then
		io_status_fatal "tag '$1' already exists."
	fi
}
