#!/usr/bin/env sh


has() {
	local item=$1; shift
	echo " $@ " | grep -q " $(escape $item) "
}

escape() {
	echo "$1" | sed 's/\([\.\$\*]\)/\\\1/g'
}

is_available() {
	type $1 >/dev/null 2>&1
}

lower_dashes() {
	local str="$(input_from_arg_or_stdin "$1")"
	echo "$str" | sed 's/-/_/g'
}

input_from_arg_or_stdin() {
	local arg
	if (( $# == 0 )) ; then
		arg="$(< /dev/stdin)"
	else
		arg=$1
	fi
	echo "$arg"
}