#!/usr/bin/env sh

                               
validate_arg() {
	if [[ -z $1 ]]; then
		usage
	fi
}

validate_le_gitflow_initialized() {
	if [[ -z $(git config --global le-gitflow.initialized) ]]; then
		fatal "le-gitflow is not initialized. you have to run 'git le init' first."
	fi
}

validate_git_clean_working_tree() {
	if ! git_is_clean_working_tree; then
		fatal "working tree is not clean. please make sure all changes are commited, or stash them." 
	fi
}
