#!/usr/bin/env sh

usage() {
    echo "usage: git le wat [name]"
    echo
}

cmd_wat() {
    if [ "$#" -lt 1 ]; then
        say_hello World; exit 0
    elif [ "$#" -eq 1 ]; then
        if [ $1 == "help" ]; then
            usage; exit 0
        fi

        say_hello $1; exit 0
    fi

    usage; exit 1
}

say_hello() {
    echo "Hello ${1}"
    echo
}